### ISSUE TITLE
Cockpit 239 - Topolgy page doesn't work

### ISSUE THREAD

**Issue by flash370** [SiliconLabs/wisun-br-gui#1]
There is a Security Policy directive violation.

Presssing CTRL-Shift-J on Chrome shows this error:

Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self' https://10.0.1.3:9090". Either the 'unsafe-inline' keyword, a hash ('sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q='), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.

Ee @ index.js:25

**Comment by flash370** [comment]
update:
I have three BRD4002A with EFR32xG28 Radio Board.
I switched a board with the BR and it works.
The two boards now works.

So, the problem still exist, but it isn't a Security Policy violation.

**Comment by silabs-AyoubA** [comment]
Please specify what version of wsbrd/RCP you are using. 
If I understand correctly the problem is just with one of the boards that you have, right? what is the problem exactly? are you able to see the two other boards on the topology?
Any additional details that can help us understand the issue and reproduce it are welcome.
Thanks,

**Comment by flash370** [comment]
Hi,

These are the first two rows of my journalctl when the BR starts:
Apr 09 15:54:13 raspberrypi wsbrd[3459]: Silicon Labs Wi-SUN border router v1.9
Apr 09 15:54:14 raspberrypi wsbrd[3459]: Connected to RCP "2.0.0" (1.3.1), API 2.0.0

The strange thing is that now I reversed the two boards (FFN and RPC) and works....
....so I think that somethink was cashed in the first test.

I alert you if I have other issues.

I does not made any modify on my setup except the switch of the two board and some reboots of my raspberry.....

**Comment by silabs-NikhilS** [comment]
Hi, 

I have the same issue, the topology page doesn't seem to load up. I have xG28 board as RCP 

I get following error on the javascript 

![Topology java script error](https://github.com/SiliconLabs/wisun-br-gui/assets/71440373/a66e238f-d075-494b-94cf-375e0055ce44)

![image](https://github.com/SiliconLabs/wisun-br-gui/assets/71440373/e8e0829d-4d94-4870-87a5-10bf59bddbf9)

Thanks
Nik

**Comment by silabs-AyoubA** [comment]
Hi all,

This project is incompatible with wisun-br-linux version 2.0, thank you for reporting the issue. I have added a note on the readme about this incompatibility to inform future users.

Best regards,
